version: '3.8'
services:
  cardano-node:
    build: ./cardano-node
    volumes:
      - cardano-node-data:/data
      - node-ipc:/ipc
      - ./cardano-node/keys:/usr/keys
      - ./cardano-node/scripts:/scripts

  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3000:3000'
  # cardano-wallet:
  #   image: inputoutput/cardano-wallet:2022.1.18
  #   volumes:
  #     - wallet-db:/wallet-db
  #     - node-ipc:/ipc
  #   environment:
  #     - NETWORK=testnet
  #   ports:
  #     - 8090:8090
  #   entrypoint: []
  #   command: bash -c "cardano-wallet serve --testnet /config/testnet/genesis-byron.json --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
  #   depends_on:
  #     - cardano-node


volumes:
  cardano-node-data:
  node-ipc: # wallet-db:
