version: '3.8'
services:
  cardano-node:
    build: .
    volumes:
      - cardano-node-data:/data
      - cardano-node-ipc:/ipc
      - ./keys:/usr/keys

volumes:
  cardano-node-data:
  cardano-node-ipc: